name: Generate candidates.csv

on:
  workflow_dispatch:
  schedule:
    - cron: "13 5 * * *"   # elke dag 05:13 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SPARQL → CSV
        env:
          LIMIT: "500"            # pas aan
        run: |
          python generate_candidates.py

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: candidates
          path: data/candidates.csv
