name: Generate candidates.csv

on:
  workflow_dispatch:
  schedule:
    - cron: '13 5 * * *'  # dagelijks 05:13 UTC

permissions:
  contents: write   # nodig om terug te committen naar de repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # nodig om te kunnen pushen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run SPARQL → CSV
        env:
          LIMIT: '200'
        run: |
          mkdir -p data
          python generate_candidates.py

      - name: Debug list files
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "---- data/"
          ls -la data || true
          echo "---- head of CSV ----"
          head -n 5 data/candidates.csv || true

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: candidates
          path: data/candidates.csv
          if-no-files-found: error

      - name: Commit CSV back to repo
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/candidates.csv
          if git commit -m "Update candidates.csv [skip ci]"; then
            git push
          else
            echo "No changes to commit."
          fi

      - name: Save timestamped snapshot (optioneel)
        run: |
          ts=$(date -u +%Y%m%d_%H%M%S)
          cp data/candidates.csv data/candidates_${ts}.csv || true
          git add data/candidates_${ts}.csv || true
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Snapshot candidates_${ts}.csv [skip ci]" || true
          git push || true
